version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/tofu"
    schedule:
      interval: "weekly"
    groups:
      terraform-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
