services:
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLASK_SECRET_KEY=test-key
      - GOOGLE_CLOUD_PROJECT=test-project
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    volumes:
      - .:/app
    depends_on:
      - firestore-emulator
    command: python -m pytest test_app.py -v