permissions:
  checks: write
  pull-requests: write
  packages: write
name: CI
on:
  push:
jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          pip install pipenv ruff
          pipenv install --dev
      - name: Run lint check
        working-directory: ./app
        run: pipenv run make lint-check
      - name: Run format check
        working-directory: ./app
        run: pipenv run make format-check
      - name: Run tests
        working-directory: ./app
        run: firebase emulators:exec --only firestore "pipenv run make test-local"
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: app/test-results.xml
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          file: app/coverage.xml
          flags: unittests
      - name: Extract metadata
        if: github.ref == 'refs/heads/main'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
