name: CI
on:
  push:
jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    services:
      firestore:
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        ports:
          - 8080:8080
        options: >-
          --entrypoint="gcloud"
        env:
          CLOUDSDK_CORE_PROJECT: demo-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          pip install pipenv ruff
          pipenv install --dev
      - name: Run lint check
        working-directory: ./app
        run: pipenv run make lint-check
      - name: Run format check
        working-directory: ./app
        run: pipenv run make format-check
      - name: Run tests
        working-directory: ./app
        env:
          FIRESTORE_EMULATOR_HOST: firestore:8080
        run: pipenv run make test-local
